//! @generated by scripts/generate_icons.py. Do not edit manually.

use crate::IconProps;
use yew::prelude::*;

macro_rules! icon_component {
    ($component:ident, $function:ident, $class:literal, [$($body:tt)*], $doc:literal) => {
        #[doc = $doc]
        #[function_component($component)]
        pub fn $function(props: &IconProps) -> Html {
            html! {
                <svg
                    class={classes!("icon", $class, props.class.clone())}
                    style={props.style.clone()}
                    width={props.width.to_string()}
                    height={props.height.to_string()}
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke={props.color.clone()}
                    stroke-width={props.stroke_width.to_string()}
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    aria-hidden="true"
                >
                    $($body)*
                </svg>
            }
        }
    };
}

icon_component!(Check, check, "icon-check", [<path d="M20 6 9 17l-5-5" />], "Check icon.");
icon_component!(X, x, "icon-x", [<path d="M18 6 6 18" /> <path d="m6 6 12 12" />], "X icon.");
icon_component!(ChevronDown, chevron_down, "icon-chevron-down", [<path d="m6 9 6 6 6-6" />], "ChevronDown icon.");
icon_component!(ChevronUp, chevron_up, "icon-chevron-up", [<path d="m18 15-6-6-6 6" />], "ChevronUp icon.");
icon_component!(ChevronLeft, chevron_left, "icon-chevron-left", [<path d="m15 18-6-6 6-6" />], "ChevronLeft icon.");
icon_component!(ChevronRight, chevron_right, "icon-chevron-right", [<path d="m9 18 6-6-6-6" />], "ChevronRight icon.");
icon_component!(ChevronsUpDown, chevrons_up_down, "icon-chevrons-up-down", [<path d="m7 15 5 5 5-5" /> <path d="m7 9 5-5 5 5" />], "ChevronsUpDown icon.");
icon_component!(Calendar, calendar, "icon-calendar", [<path d="M8 2v3" /> <path d="M16 2v3" /> <rect x="3" y="3" width="18" height="18" rx="2" /> <path d="M3 9h18" />], "Calendar icon.");
icon_component!(Search, search, "icon-search", [<path d="m21 21-4.34-4.34" /> <circle cx="11" cy="11" r="8" />], "Search icon.");
icon_component!(Menu, menu, "icon-menu", [<path d="M4 5h16" /> <path d="M4 12h16" /> <path d="M4 19h16" />], "Menu icon.");
icon_component!(Ellipsis, ellipsis, "icon-ellipsis", [<circle cx="12" cy="12" r="1" /> <circle cx="19" cy="12" r="1" /> <circle cx="5" cy="12" r="1" />], "Ellipsis icon.");
icon_component!(PanelLeft, panel_left, "icon-panel-left", [<rect width="18" height="18" x="3" y="3" rx="2" /> <path d="M9 3v18" />], "PanelLeft icon.");
icon_component!(PanelRight, panel_right, "icon-panel-right", [<rect width="18" height="18" x="3" y="3" rx="2" /> <path d="M15 3v18" />], "PanelRight icon.");
icon_component!(CircleAlert, circle_alert, "icon-circle-alert", [<circle cx="12" cy="12" r="10" /> <line x1="12" x2="12" y1="8" y2="12" /> <line x1="12" x2="12.01" y1="16" y2="16" />], "CircleAlert icon.");
icon_component!(CircleCheck, circle_check, "icon-circle-check", [<circle cx="12" cy="12" r="10" /> <path d="m16 9-5.5 5.5L8 12" />], "CircleCheck icon.");
icon_component!(Info, info, "icon-info", [<circle cx="12" cy="12" r="10" /> <path d="M12 16v-4" /> <path d="M12 8h.01" />], "Info icon.");
icon_component!(LoaderCircle, loader_circle, "icon-loader-circle", [<path d="M21 12a9 9 0 1 1-6.219-8.56" />], "LoaderCircle icon.");
icon_component!(Trash, trash, "icon-trash", [<path d="M10 11v6" /> <path d="M14 11v6" /> <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" /> <path d="M3 6h18" /> <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />], "Trash icon.");
icon_component!(Plus, plus, "icon-plus", [<path d="M5 12h14" /> <path d="M12 5v14" />], "Plus icon.");
icon_component!(Minus, minus, "icon-minus", [<path d="M5 12h14" />], "Minus icon.");
icon_component!(Sun, sun, "icon-sun", [<circle cx="12" cy="12" r="4" /> <path d="M12 2v2" /> <path d="M12 20v2" /> <path d="m4.93 4.93 1.41 1.41" /> <path d="m17.66 17.66 1.41 1.41" /> <path d="M2 12h2" /> <path d="M20 12h2" /> <path d="m6.34 17.66-1.41 1.41" /> <path d="m19.07 4.93-1.41 1.41" />], "Sun icon.");
icon_component!(Moon, moon, "icon-moon", [<path d="M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401" />], "Moon icon.");
icon_component!(ArrowLeft, arrow_left, "icon-arrow-left", [<path d="m12 19-7-7 7-7" /> <path d="M19 12H5" />], "ArrowLeft icon.");
icon_component!(ArrowRight, arrow_right, "icon-arrow-right", [<path d="M5 12h14" /> <path d="m12 5 7 7-7 7" />], "ArrowRight icon.");
icon_component!(ArrowUp, arrow_up, "icon-arrow-up", [<path d="m5 12 7-7 7 7" /> <path d="M12 19V5" />], "ArrowUp icon.");
icon_component!(ArrowDown, arrow_down, "icon-arrow-down", [<path d="M12 5v14" /> <path d="m19 12-7 7-7-7" />], "ArrowDown icon.");
icon_component!(Settings, settings, "icon-settings", [<path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915" /> <circle cx="12" cy="12" r="3" />], "Settings icon.");
icon_component!(User, user, "icon-user", [<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" /> <circle cx="12" cy="7" r="4" />], "User icon.");
icon_component!(Users, users, "icon-users", [<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" /> <path d="M16 3.128a4 4 0 0 1 0 7.744" /> <path d="M22 21v-2a4 4 0 0 0-3-3.87" /> <circle cx="9" cy="7" r="4" />], "Users icon.");
icon_component!(House, house, "icon-house", [<path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8" /> <path d="M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />], "House icon.");
icon_component!(Mail, mail, "icon-mail", [<path d="m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7" /> <rect x="2" y="4" width="20" height="16" rx="2" />], "Mail icon.");
icon_component!(Phone, phone, "icon-phone", [<path d="M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384" />], "Phone icon.");
icon_component!(MapPin, map_pin, "icon-map-pin", [<path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0" /> <circle cx="12" cy="10" r="3" />], "MapPin icon.");
icon_component!(ExternalLink, external_link, "icon-external-link", [<path d="M15 3h6v6" /> <path d="M10 14 21 3" /> <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />], "ExternalLink icon.");
icon_component!(Link, link, "icon-link", [<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" /> <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />], "Link icon.");
icon_component!(Unlink, unlink, "icon-unlink", [<path d="m18.84 12.25 1.72-1.71h-.02a5.004 5.004 0 0 0-.12-7.07 5.006 5.006 0 0 0-6.95 0l-1.72 1.71" /> <path d="m5.17 11.75-1.71 1.71a5.004 5.004 0 0 0 .12 7.07 5.006 5.006 0 0 0 6.95 0l1.71-1.71" /> <line x1="8" x2="8" y1="2" y2="5" /> <line x1="2" x2="5" y1="8" y2="8" /> <line x1="16" x2="16" y1="19" y2="22" /> <line x1="19" x2="22" y1="16" y2="16" />], "Unlink icon.");
icon_component!(Copy, copy, "icon-copy", [<rect width="14" height="14" x="8" y="8" rx="2" ry="2" /> <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />], "Copy icon.");
icon_component!(Clipboard, clipboard, "icon-clipboard", [<rect width="8" height="4" x="8" y="2" rx="1" ry="1" /> <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />], "Clipboard icon.");
icon_component!(Pen, pen, "icon-pen", [<path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z" />], "Pen icon.");
icon_component!(Download, download, "icon-download", [<path d="M12 15V3" /> <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /> <path d="m7 10 5 5 5-5" />], "Download icon.");
icon_component!(Upload, upload, "icon-upload", [<path d="M12 3v12" /> <path d="m17 8-5-5-5 5" /> <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />], "Upload icon.");
icon_component!(Funnel, funnel, "icon-funnel", [<path d="M10 20a1 1 0 0 0 .553.895l2 1A1 1 0 0 0 14 21v-7a2 2 0 0 1 .517-1.341L21.74 4.67A1 1 0 0 0 21 3H3a1 1 0 0 0-.742 1.67l7.225 7.989A2 2 0 0 1 10 14z" />], "Funnel icon.");
icon_component!(SlidersHorizontal, sliders_horizontal, "icon-sliders-horizontal", [<path d="M10 5H3" /> <path d="M12 19H3" /> <path d="M14 3v4" /> <path d="M16 17v4" /> <path d="M21 12h-9" /> <path d="M21 19h-5" /> <path d="M21 5h-7" /> <path d="M8 10v4" /> <path d="M8 12H3" />], "SlidersHorizontal icon.");
icon_component!(RefreshCw, refresh_cw, "icon-refresh-cw", [<path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" /> <path d="M21 3v5h-5" /> <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" /> <path d="M8 16H3v5" />], "RefreshCw icon.");
icon_component!(LogOut, log_out, "icon-log-out", [<path d="m16 17 5-5-5-5" /> <path d="M21 12H9" /> <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />], "LogOut icon.");
icon_component!(LogIn, log_in, "icon-log-in", [<path d="m10 17 5-5-5-5" /> <path d="M15 12H3" /> <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />], "LogIn icon.");
icon_component!(Bell, bell, "icon-bell", [<path d="M10.268 21a2 2 0 0 0 3.464 0" /> <path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326" />], "Bell icon.");
icon_component!(Bookmark, bookmark, "icon-bookmark", [<path d="M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z" />], "Bookmark icon.");
icon_component!(Star, star, "icon-star", [<path d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z" />], "Star icon.");
icon_component!(Heart, heart, "icon-heart", [<path d="M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5" />], "Heart icon.");
icon_component!(Image, image, "icon-image", [<rect width="18" height="18" x="3" y="3" rx="2" ry="2" /> <circle cx="9" cy="9" r="2" /> <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />], "Image icon.");
icon_component!(Folder, folder, "icon-folder", [<path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />], "Folder icon.");
icon_component!(File, file, "icon-file", [<path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z" /> <path d="M14 2v5a1 1 0 0 0 1 1h5" />], "File icon.");
icon_component!(Clock3, clock_3, "icon-clock-3", [<circle cx="12" cy="12" r="10" /> <path d="M12 6v6h4" />], "Clock3 icon.");
icon_component!(Sparkles, sparkles, "icon-sparkles", [<path d="M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z" /> <path d="M20 2v4" /> <path d="M22 4h-4" /> <circle cx="4" cy="20" r="2" />], "Sparkles icon.");
