#!/usr/bin/env python3
"""Generate shadcn-icons from Lucide SVG sources."""

from __future__ import annotations

import argparse
import re
import sys
import urllib.error
import urllib.request
import xml.etree.ElementTree as et
from pathlib import Path

LUCIDE_RAW_BASE = "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons"


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def component_name(icon_name: str) -> str:
    return "".join(part.capitalize() for part in icon_name.split("-"))


def function_name(icon_name: str) -> str:
    return icon_name.replace("-", "_")


def rust_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_tag(element: et.Element) -> str:
    tag_name = element.tag.split("}", 1)[-1]
    attributes = " ".join(
        f'{name}={rust_string(value)}' for name, value in element.attrib.items()
    )
    if len(element):
        children = "".join(render_tag(child) for child in element)
        return f"<{tag_name} {attributes}>{children}</{tag_name}>"
    return f"<{tag_name} {attributes} />"


def fetch_svg(icon_name: str) -> str:
    try:
        with urllib.request.urlopen(f"{LUCIDE_RAW_BASE}/{icon_name}.svg") as response:
            return response.read().decode("utf-8")
    except urllib.error.HTTPError as exc:  # type: ignore[attr-defined]
        raise RuntimeError(f"failed to fetch Lucide icon '{icon_name}': HTTP {exc.code}") from exc


def load_icon_names(manifest: Path) -> list[str]:
    names: list[str] = []
    for line in manifest.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if not re.fullmatch(r"[a-z0-9-]+", line):
            raise ValueError(f"invalid icon name in manifest: {line}")
        names.append(line)
    return names


def generate_module(icon_names: list[str]) -> str:
    lines = [
        "//! @generated by scripts/generate_icons.py. Do not edit manually.",
        "",
        "use crate::IconProps;",
        "use yew::prelude::*;",
        "",
        "macro_rules! icon_component {",
        "    ($component:ident, $function:ident, $class:literal, [$($body:tt)*], $doc:literal) => {",
        "        #[doc = $doc]",
        "        #[function_component($component)]",
        "        pub fn $function(props: &IconProps) -> Html {",
        "            html! {",
        "                <svg",
        '                    class={classes!("icon", $class, props.class.clone())}',
        "                    style={props.style.clone()}",
        "                    width={props.width.to_string()}",
        "                    height={props.height.to_string()}",
        '                    viewBox="0 0 24 24"',
        '                    fill="none"',
        "                    stroke={props.color.clone()}",
        "                    stroke-width={props.stroke_width.to_string()}",
        '                    stroke-linecap="round"',
        '                    stroke-linejoin="round"',
        '                    aria-hidden="true"',
        "                >",
        "                    $($body)*",
        "                </svg>",
        "            }",
        "        }",
        "    };",
        "}",
        "",
    ]

    for icon_name in icon_names:
        svg = fetch_svg(icon_name)
        root = et.fromstring(svg)
        children = " ".join(render_tag(child) for child in root)
        lines.append(
            f"icon_component!("
            f"{component_name(icon_name)}, "
            f"{function_name(icon_name)}, "
            f"{rust_string(f'icon-{icon_name}')}, "
            f"[{children}], "
            f"{rust_string(f'{component_name(icon_name)} icon.')}"
            f");"
        )

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        default="shadcn-icons/icons.txt",
        help="path to the icon manifest relative to the repo root",
    )
    parser.add_argument(
        "--output",
        default="shadcn-icons/src/generated.rs",
        help="generated Rust module path relative to the repo root",
    )
    args = parser.parse_args()

    root = repo_root()
    manifest = root / args.manifest
    output = root / args.output

    icon_names = load_icon_names(manifest)
    output.write_text(generate_module(icon_names))
    print(f"generated {len(icon_names)} icons into {output.relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
